GET http://localhost:3001/api/persons
###

GET http://localhost:3001/api/persons/629b4f5bd3d39760b5359d78
###

DELETE http://localhost:3001/api/persons/629bab3739991d486f4adf5f
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "lsoq",
    "number": "12-1212e12"
}
###

PUT http://localhost:3001/api/persons/629bab3739991d486f4adf5f
Content-Type: application/json

{
    "name": "loq",
    "number": "33-010101"
}