GET http://localhost:3001/api/persons
###

GET http://localhost:3001/api/persons
###

DELETE http://localhost:3001/api/persons/62967a416642295041d7cea7
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "lu",
    "number": "1234223"
}
###

PUT http://localhost:3001/api/persons/629668d6586b4c2689b03dab
Content-Type: application/json

{
    "name": "lo",
    "number": "sss"
}